### PR TITLE
Added server mode fuzzing support in winAFL

### PR DESCRIPTION
**Pull request by mxmssh**
1) WinAFL now supports server mode fuzzing to test clients. User need to specify a third-party DLL where he/she should define communication logic with a client.
2) Added default server DLL for winAFL.
3) Added test for server-mode fuzzing support.

### CODE REVIEW

**Comment by ivanfratric** [comment]
This is interesting and I really like the idea of plugging a dll for sample delivery. Which got me thinking if perhaps there is a generic way to do this that would work for both client- and server-side fuzzing as well as for potentially any other sample delivery method.

The basic idea is: whenever you want to deliver a sample to the target in a custom way, you would provide a dll which (like in the case of your code) would expose two methods, an initialization one, and one to deliver the sample.

Then instead of

```
if (enable_socket_fuzzing && !enable_server_mode)
  open_file_and_send_data();
else if (enable_server_mode)
  process_test_case_into_server();
```

Then you have now, you coud simply do something along the lines of

```
if(custom_send_sample)
  custom_send_sample();
```

And all of the network-specific code could be moved to client and server fuzzing dlls.

The benefit of this wold be more modular design and easier to do changes for custom protocols and delivery mechanisms. For example, the current network fuzzing sends all of the sample at once, but if you needed to do something more complicated you could just change the client fuzzing dll and not the main afl-fuzz binary (which is quite bloated as is anyway), it would be easier to do other custom delivery mechanisms (e.g. deliver a sample via pipe) etc.

What do you think?

**Comment by mxmssh** [comment]
Yes, I thought about this idea but was too lazy to implement it :) Ok, let's do it. The next commit in this branch will support this. There is only one question. How do we want our user to send arguments in the DLL? We can ask for a list of arguments via console but in my opinion winAFL command line is already a bit long. So, I am thinking about configuration file. The user only need to specify a path to this config file where he/she can define custom list of arguments to be supported in this third-party DLL.

What do you think?

**Comment by ivanfratric** [comment]
Cool!

Yes, passing the arguments is a good question. The things I considered were

 - passing the arguments to the dll via an environment variable

 - passing the winafl argv+argc when when calling the initialization method. That way dll can use any flag names unused by WinAFL

 - having a separate flag for parameters passed to the dll, e.g. `-x ip:port` or `-x "-ip <ip> -port <port>"`

 But certainly, a config file for the dll works as well.

I don't really have a strong feeling about any of this. But perhaps the best way is to leave the decision to the dll author. So for example, we could still pass argv+argc to the dll initialization method, but if the dll author prefers to use an environment variable or a config file, they can just ignore the command line arguments. And then for your dlls (client and server fuzzing) you can use whatever you think makes the most sense.

**Comment by mxmssh** [comment]
Ok, finally, end up with environment variables.

**Comment by ivanfratric** [comment]
Looks great! The only comment I have is about the enable_socket_fuzzing (-s) flag. I think that it is not necessary anymore for it to be an afl-fuzz flag since afl-fuzz doesn't actually use it and just passes it to winafl client. Instead, the user can just add -socket_fuzzing to the instrumentation options. Furthermore, -socket_fuzzing name is now a bit misleading, since (a) it will likely be usable for other delivery mechanisms other than sockets and (b) the actual meaning of the flag now is simply to prevent forcibly looping over the target_method, so it could be called -no_loop or something to that effect (I'm open to other suggestions).

**Comment by mxmssh** [comment]
Yes, it makes sense. Also, I found that winAFL actually already supports this behavior via In App Persistance mode :) So, I get rid of -s option at all. PTAL the new commit.

**Comment by ivanfratric** [comment]
I considered taking advantage of the In App Persistance mode here, but one major difference between In App Persistance mode and the "default" mode is that in the "default" mode, the end of an iteration happens when the target function returns, while in the "In App Persistance" the end of an iteration happens when the target function is _re-entered_, see when `WriteCommandToPipe('K')` happens in both of those cases.

I wasn't sure if the latter would work here, which is why I didn't suggest it. For example, if in the network fuzzing mode the user selects a target function which is only (re-)entered once a connection is established, since in the network fuzzing mode the new connection is only established once a previous iteration ends, the first iteration would never end and afl-fuzz would be stuck waiting for that 'K' signal.

Do you think it can still made to work somehow?

**Comment by mxmssh** [comment]
Hm, I see the difference. I guess it depends on program. Suppose we have the following program:
```
ConnectionHandler :
    ...
    recv();
    parse_data();
    ...
    return;

functionA: 
    ...
    accept();
    ConnectionHandler();
    ...
    return;

main:
    ...
    while (1):
        functionA();
    ...
    return;
```

In this case, user can select functionA where accept() actually called instead of ConnectionHandler. 
However, if our program looks like this:
```
ConnectionHandler :
    ...
    recv();
    parse_data();
    ...
    return;

main:
    ...
    while (1):
        accept();
        ConnectionHandler();
    ...
    return;
```
In this case, yes, this ```-s``` or ```-no_loop``` option might be usefull. I didn't think about this. Let's return it ? :)

**Comment by ivanfratric** [comment]
Sorry for a late reply, was AFK for a couple of days. Agreed on returning the flag. I think it can be just an instrumentation (winafl.c) flag, no need to make it an afl-fuzz flag as discussed previously.

**Comment by ifratric** [comment]
Awesome! This is a pretty sweet update - thank you for working on it!

**Pull request merged**
