### PR TITLE
winafl-cmin: Log command line arguments

### PR DESCRIPTION
**Pull request by moshekaplan**

### CODE REVIEW

**Comment by moshekaplan** [comment]
Sample launch command:
`python3 C:\Users\moshe\Desktop\winafl_dev\winafl-cmin.py -w 1 --working-dir C:\Users\moshe\Desktop\fuzz\winafl\build32\bin\Release -i C:\Users\moshe\Desktop\fuzz\corpus_combined -o C:\Users\moshe\Desktop\fuzz\Fuzz_Formats_ReadCMP_cmin -t 4000 -D C:\Users\moshe\Desktop\fuzz\dynamorio\build\bin32 -covtype edge -coverage_module "Fuzz_Formats_ReadCMP.exe" -coverage_module "FORMATS.DLL" -target_module "Fuzz_Formats_ReadCMP.exe" -target_method "call_ReadCMP" -nargs 1 -- "C:\Users\moshe\Desktop\fuzz\Fuzz_Irfanview_Harness\Release\Fuzz_Formats_ReadCMP.exe" @@`

Sample output:
`2021-04-26 10:43:11,131 [DEBUG] [main] [+] winafl-cmin called with the following arguments: C:\Users\moshe\Desktop\winafl_dev\winafl-cmin.py -w 1 --working-dir C:\Users\moshe\Desktop\fuzz\winafl\build32\bin\Release -i C:\Users\moshe\Desktop\fuzz\corpus_combined -o C:\Users\moshe\Desktop\fuzz\Fuzz_Formats_ReadCMP_cmin -t 4000 -D C:\Users\moshe\Desktop\fuzz\dynamorio\build\bin32 -covtype edge -coverage_module Fuzz_Formats_ReadCMP.exe -coverage_module FORMATS.DLL -target_module Fuzz_Formats_ReadCMP.exe -target_method call_ReadCMP -nargs 1 -- C:\Users\moshe\Desktop\fuzz\Fuzz_Irfanview_Harness\Release\Fuzz_Formats_ReadCMP.exe @@`

**Comment by ifratric** [comment]
Just wondering what the reason behind this change is. I mean, won't the user see the command line arguments anyway?

**Comment by moshekaplan** [comment]
The log file lasts longer than the terminal - it's possible the terminal window will close, the buffer will be filled, or running another tool will overwrite the afl-cmin text.

**Comment by ifratric** [comment]
So, normally I'd consider logging the arguments to be the responsibility of the caller, but given how Windows terminal does not have history, I see this could be occasionally useful.

**Pull request merged**
