### PR TITLE
Update CVEs

### PR DESCRIPTION
**Pull request by sgabe**
This PR updates the known CVEs with the recent findings of Valentino Ricotta. Unfortunately, I could not find any direct contacts of Valentino.

### CODE REVIEW

**Comment by symeonp** [comment]
Hey Gabor, it looks like they're on twitter and have email information: https://thalium.github.io/blog/posts/

**Comment by ifratric** [comment]
Thanks @sgabe and @symeonp. @sgabe will you reach out to the author or shall I? I actually feel quite strongly about only listing people here with their knowledge and approval.

**Comment by sgabe** [comment]
I have sent an approval request email to the Thalium team, asking them to leave a comment here.

**Comment by face0xff** [comment]
Hey, I am the author of these CVEs and I approve being listed here. Thanks! 🙂

**Comment by ifratric** [comment]
Awesome, thanks all! And congrats on the CVEs @face0xff !

**Pull request merged**
