### PR TITLE
Check python scripts for issues

### PR DESCRIPTION
**Pull request by moshekaplan**

### CODE REVIEW

**Comment by moshekaplan** [comment]
I set it to ignore E501, line too long, as there can be legitimate reasons for lines to be more than 80 characters long.

**Comment by ifratric** [comment]
I think we'd need to fix existing issues before merging this one :-)

**Comment by ifratric** [comment]
Ok, so, after a moment of thought and before I proceed with the related changes

 - I think if style guide should be enforced, it should be Google's python style guide which relies on pylint, see https://google.github.io/styleguide/pyguide.html

 - I have doubts about applying a style guide for winafl repo. The main purpose of WinAfl was always to be compatible with AFL, and enforcing a style guide here might make it harder to port features from the "upstream" AFL (assuming any features we want to port get added), in the case other repo follows a different style guide or doesn't follow a style guide.

**Comment by moshekaplan** [comment]
I added flake8, not because I cared about style issues, but to check for errors within the code, like using undefined variables, broken indentation, and other similar issues that would cause the script to stop execution.

**Comment by ifratric** [comment]
I think I'll skip this one. The intention is good but I think in practice it is going to be more annoying then helpful e.g. most of the issues it found are related to styling and not actual issues.

**Comment by ifratric** [comment]
I'll leave it to you whether you want to leave the remaining lake8 PR ("winafl-cmin.py: Fix flake8 issues") or close it. I don't mind accepting that one.

**Pull request closed without merging**
