### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by eranzim**
Fix a few compilation and static analysis warnings (which look correct and fairly trivial to fix)

### CODE REVIEW

**Comment by eranzim** [comment]
The commits were made with a different email address than the one associated with my github account. I added this address as an alternate address to my google profile, as explained in the link, I hope it works now (and if not - what should I do?)
Thanks!

**Comment by eranzim** [comment]
@googlebot I signed it!

**Comment by ifratric** [comment]
Hey Eran, thanks for the PR! Just a quick note that I'm on vacation and will take a closer look when I get back after New Year. I'll check the CLA stuff then as well (I need my work computer for that).

**Comment by ifratric** [comment]
Thanks for the PR, looks good to me! The CLA check passed after forcing a rescan.

**Pull request merged**
